build-and-test:
  image: ocaml/opam2:alpine-3.10-ocaml-4.08
  script:
    - opam pin --no-action data-encoding .
    - opam depext ocamlformat.0.11.0
    - opam install ocamlformat.0.11.0
    - dune build @fmt
    - opam depext data-encoding
    - opam install --deps-only data-encoding
    - dune build
    - opam depext --dry-run crowbar alcotest
    - opam install --deps-only --with-test .
    - dune runtest
